### ISSUE TITLE
Rapport Debrief du sprint 1 pas bien renseigné

### ISSUE THREAD

**Issue by KevinBdn** [Equipe-tennis/CollecteBalle#5]
Merci de remplir convenablement le rapport `Debrief` du sprint 1:
https://github.com/Equipe-tennis/CollecteBalle/blob/830016f2daae8c2be9882bc2d8c3915ac5f3de64/reports/01_Debrief.md?plain=1#L3-L26

**Comment by HugoGace** [comment]
fait
